export const GET_NEW_PIZZAS_REQUEST = "GET_NEW_PIZZAS_REQUEST";
export const GET_NEW_PIZZAS_SUCCESS = "GET_NEW_PIZZAS_SUCCESS";
export const GET_NEW_PIZZAS_FAILURE = "GET_NEW_PIZZAS_FAILURE";

export const UPDATE_NEW_PIZZAS_REQUEST = "UPDATE_NEW_PIZZAS_REQUEST";
export const UPDATE_NEW_PIZZAS_SUCCESS = "UPDATE_NEW_PIZZAS_SUCCESS";
export const UPDATE_NEW_PIZZAS_FAILURE = "UPDATE_NEW_PIZZAS_FAILURE";

export const GET_NEW_PIZZA_REQUEST = "GET_NEW_PIZZA_REQUEST";
export const GET_NEW_PIZZA_SUCCESS = "GET_NEW_PIZZA_SUCCESS";
export const GET_NEW_PIZZA_FAILURE = "GET_NEW_PIZZA_FAILURE";
