export const GET_PIZZA_REQUEST = "GET_PIZZA_REQUEST";
export const GET_PIZZA_SUCCESS = "GET_PIZZA_SUCCESS";
export const GET_PIZZA_FAILURE = "GET_PIZZA_FAILURE";

export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILURE = "GET_PIZZAS_FAILURE";
